version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt -t ./package
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build phase
      - zip -r function.zip .
  post_build:
    commands:
      - echo Post-build phase
      - aws lambda update-function-code --function-name ProcessDoorDashDeliveries --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
